name: projeto_pdm
description: Um aplicativo para que leitores encontrem novos livros de maneira mais fácil, apresentando reviews de outros leitores, gêneros e tags correspondentes aos livros cadastrados na plataforma.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  provider: ^6.0.5
  cloud_firestore: ^4.12.2
  sqflite: ^2.3.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/img/
  - assets/fonts/

fonts:
  - family: EduTASBeginner
    fonts:
      - asset: assets/fonts/EduTASBeginner-Regular.ttf
        style: regular
        weight: 400
      - asset: assets/fonts/EduTASBeginner-Medium.ttf
        style: medium
        weight: 500
      - asset: assets/fonts/EduTASBeginner-SemiBold.ttf
        style: semibold
        weight: 600
      - asset: assets/fonts/EduTASBeginner-Bold.ttf
        style: bold
        weight: 700
  - family: Exo2
    fonts:
      - asset: assets/fonts/Exo2-Light.ttf
        style: light
        weight: 300
      - asset: assets/fonts/Exo2-Regular.ttf
        style: regular 
        weight: 400
      - asset: assets/fonts/Exo2-Medium.ttf
        style: medium
        weight: 500
      - asset: assets/fonts/Edxo2-SemiBold.ttf
        style: semibold
        weight: 600
      - asset: assets/fonts/Exo2-Bold.ttf
        style: bold
        weight: 700


  